coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: yes
