#  This file is part of Pynguin.
#
#  SPDX-FileCopyrightText: 2019–2021 Pynguin Contributors
#
#  SPDX-License-Identifier: LGPL-3.0-or-later
#
from pynguin.generation.export.pytestexporter import PyTestExporter


def test_export_sequence(exportable_test_case, tmp_path):
    path = tmp_path / "generated.py"
    exporter = PyTestExporter()
    exporter.export_sequences(str(path), [exportable_test_case, exportable_test_case])
    assert (
        path.read_text()
        == """# Automatically generated by Pynguin.
import pytest
import tests.fixtures.accessibles.accessible as module0


def test_case_0():
    int0 = 5
    some_type0 = module0.SomeType(int0)
    assert some_type0 == 5
    float0 = 42.23
    float1 = module0.simple_function(float0)
    assert float1 == pytest.approx(42.23, abs=0.01, rel=0.01)


def test_case_1():
    int0 = 5
    some_type0 = module0.SomeType(int0)
    assert some_type0 == 5
    float0 = 42.23
    float1 = module0.simple_function(float0)
    assert float1 == pytest.approx(42.23, abs=0.01, rel=0.01)
"""
    )
