#  This file is part of Pynguin.
#
#  SPDX-FileCopyrightText: 2019–2022 Pynguin Contributors
#
#  SPDX-License-Identifier: LGPL-3.0-or-later
#

# Automatically generated by Pynguin.
import example as module_0


def test_case_0():
    int_0 = -842
    int_1 = -808
    str_0 = module_0.triangle(int_0, int_0, int_1)
    assert str_0 == "Isosceles triangle"


def test_case_1():
    int_0 = -690
    int_1 = 4296
    str_0 = module_0.triangle(int_0, int_1, int_1)
    assert str_0 == "Isosceles triangle"


def test_case_2():
    int_0 = 1880
    int_1 = 279
    int_2 = 187
    int_3 = 1231
    str_0 = module_0.triangle(int_1, int_2, int_3)
    assert str_0 == "Scalene triangle"
    str_1 = module_0.triangle(int_0, int_0, int_0)
    assert str_1 == "Equilateral triangle"


def test_case_3():
    int_0 = -2442
    int_1 = 748
    int_2 = 206
    str_0 = module_0.triangle(int_1, int_1, int_2)
    assert str_0 == "Isosceles triangle"
    int_3 = -3241
    int_4 = 549
    int_5 = 996
    str_1 = module_0.triangle(int_3, int_4, int_5)
    assert str_1 == "Scalene triangle"
    str_2 = module_0.triangle(int_0, int_3, int_0)
    assert str_2 == "Isosceles triangle"
