# This file is part of Pynguin.
#
# SPDX-FileCopyrightText: 2019–2026 Pynguin Contributors
# SPDX-FileCopyrightText: 2023 Microsoft
#
# SPDX-License-Identifier: MIT
#
"""Holds logic for rewriting code generated by LLM into a format closer to Pynguin's.

The logic is adapted from the CodaMosa repository with additional refactoring.
https://github.com/microsoft/codamosa
"""

import ast
import dataclasses
import logging
import re
import sys
from typing import Any

logger = logging.getLogger(__name__)


def _has_zero_arg_super(node: ast.AST) -> bool:
    """Check if node contains a zero-argument super() call.

    Args:
        node: The AST node to check.

    Returns:
        True if a zero-argument super() call is present, False otherwise.
    """
    for child in ast.walk(node):
        if (
            isinstance(child, ast.Call)
            and isinstance(child.func, ast.Name)
            and child.func.id == "super"
            and not child.args
            and not child.keywords
        ):
            return True
    return False


class StmtRewriter(ast.NodeTransformer):  # noqa: PLR0904
    """Rewrites a statement as much as possible.

    - If it can be rewritten as an assignment statement, write it as an assignment.
    - Each child expression of the expression on the statement's RHS is rewritten,
      so it is a variable reference, and a variable assignment is added defining
      that variable to the correct expression.

    Exceptions:
        - Currently don't recurse into function definitions or lambdas.
        - Call expressions are allowed to have a single-level attribute
          expression as the function being called.
    """

    def __init__(self):  # noqa: D107
        self.stmts_to_add: list[ast.stmt] = []
        # We don't track this in e.g. function calls because there
        # are no scoping issues in extracting subexpressions there
        self._bound_variables: set[str] = set()
        self.replace_only_free_subnodes = False

        self._bound_variables_stack: list[set[str]] = []
        self._replace_only_free_stack: list[bool] = []

        # State that matters for block-level scoping
        self.used_varnames: set[str] = set()
        self.var_counter = 0
        self.constant_dict = {}
        self.used_varnames_stack: list[set[str]] = []
        self.var_counter_stack: list[int] = []
        self.constant_dict_stack: list[dict[Any, ast.Name]] = []
        super().__init__()

    def reset_stmts_to_add(self):
        """Call after visit to avoid adding redundant statements."""
        self.stmts_to_add = []

    def generate_new_varname(self):
        """Get a fresh variable name in format var_X.

        Returns:
            a new variable name.
        """
        new_varname = "var_" + str(self.var_counter)
        self.var_counter += 1
        while new_varname in self.used_varnames:
            new_varname = "var_" + str(self.var_counter)
            self.var_counter += 1
        self.used_varnames.add(new_varname)
        return new_varname

    def replace_with_varname(self, node):
        """Returns the node directly without hoisting sub-expressions into assignments.

        Args:
            node: an ast Node.

        Returns:
            the node itself.
        """
        return node

    def enter_new_block_scope(self):
        """Call when entering a new variable name scope."""
        self.used_varnames_stack.append(self.used_varnames)
        self.var_counter_stack.append(self.var_counter)
        self.constant_dict_stack.append(self.constant_dict)
        self.used_varnames = set()
        self.var_counter = 0
        self.constant_dict = {}

    def exit_block_scope(self):
        """Call when exiting a new variable name scope."""
        self.used_varnames = self.used_varnames_stack.pop()
        self.var_counter = self.var_counter_stack.pop()
        self.constant_dict = self.constant_dict_stack.pop()

    def enter_new_bound_scope(self):
        """Call when visiting an expression that creates new bound vars."""
        self._bound_variables_stack.append(set(self._bound_variables))
        self._replace_only_free_stack.append(self.replace_only_free_subnodes)
        self.replace_only_free_subnodes = True

    def exit_bound_scope(self):
        """Call when done visiting an expression that creates new bound vars."""
        self._bound_variables = self._bound_variables_stack.pop()
        self.replace_only_free_subnodes = self._replace_only_free_stack.pop()

    def get_stmts_to_add(self):
        """Get all the assignment statements that were created while visiting.

        Returns:
            the statements that were added during the visit.
        """
        return self.stmts_to_add

    def visit_block_helper(self, block: list[ast.stmt]):
        """Helper to visit a list of statements, as in a function body.

        Args:
            block: the body to visit.

        Returns:
            a list of ast statements.
        """
        self.enter_new_block_scope()
        new_body = []
        for stmt in block:
            new_stmt = self.visit(stmt)
            new_body.extend(self.get_stmts_to_add())
            self.reset_stmts_to_add()
            if new_stmt is not None:
                new_body.append(new_stmt)
        self.exit_block_scope()
        return new_body

    def generic_visit(self, node):
        """A generic visit without subnode hoisting.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        return super().generic_visit(node)

    def visit_only_calls_subnodes(self, node):
        """Same as generic_visit without hoisting.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        return self.generic_visit(node)

    def visit_Call(self, call: ast.Call):  # noqa: N802
        """Visit a call.

        Args:
            call: the call node to visit.

        Returns:
            the transformed node.
        """
        func = self.visit(call.func)
        new_args = [self.visit(arg) for arg in call.args]
        new_kwargs = [
            ast.keyword(arg=kwarg.arg, value=self.visit(kwarg.value)) for kwarg in call.keywords
        ]
        return ast.Call(func=func, args=new_args, keywords=new_kwargs)

    def visit_Subscript(self, subscript: ast.Subscript):  # noqa: N802
        """Visit subscript expression.

        Args:
            subscript: the subscript node to visit.

        Returns:
            the transformed node.
        """
        new_slice = self.visit(subscript.slice)
        new_value = self.visit(subscript.value)
        return ast.Subscript(value=new_value, slice=new_slice, ctx=subscript.ctx)

    def visit_UnaryOp(self, node):  # noqa: N802
        """Visits unary op."""
        return self.generic_visit(node)

    def visit_Attribute(self, node: ast.Attribute) -> ast.AST:  # noqa: N802
        """When visiting attribute nodes, remove self. prefix.

        Args:
            node: the attribute node to visit.

        Returns:
            the transformed node.
        """
        if isinstance(node.value, ast.Name) and node.value.id == "self":
            return ast.Name(id=node.attr, ctx=node.ctx)

        value_visited = self.visit(node.value)
        return ast.Attribute(value=value_visited, attr=node.attr, ctx=node.ctx)

    def visit_Assign(self, assign: ast.Assign):  # noqa: N802
        """When visiting an assignment statement.

        Args:
            assign: the assign node to visit.

        Returns:
            the transformed node.
        """
        for target in assign.targets:
            if isinstance(target, ast.Name):
                self.used_varnames.add(target.id)
        new_rhs = self.visit(assign.value)
        return ast.Assign(targets=assign.targets, value=new_rhs, type_comment=assign.type_comment)

    def visit_AnnAssign(self, node: ast.AnnAssign):  # noqa: N802
        """Convert annotated assigns to regular assigns.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        if node.value is not None:
            return self.visit(ast.Assign(targets=[node.target], value=node.value))
        return None

    def visit_AugAssign(self, node):  # noqa: N802
        """Convert augmented assigns to regular assigns.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        new_aug_assign = self.generic_visit(node)
        rhs_binop = ast.BinOp(
            left=new_aug_assign.target, op=new_aug_assign.op, right=new_aug_assign.value
        )
        return ast.Assign(targets=[new_aug_assign.target], value=rhs_binop)

    def visit_NamedExpr(self, node: ast.NamedExpr):  # noqa: N802
        """Transform walrus expressions to regular assigns + uses.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        rhs = self.visit(node.value)
        self.stmts_to_add.append(ast.Assign(targets=[node.target], value=rhs))
        return node.target

    def visit_Expr(self, expr: ast.Expr):  # noqa: N802
        """Visit an Expr statement.

        Args:
            expr: the node to visit.

        Returns:
            the transformed node.
        """
        if isinstance(expr.value, ast.NamedExpr):
            rhs = self.visit(expr.value.value)
            return ast.Assign(targets=[expr.value.target], value=rhs)
        if type(expr.value) in {ast.Await, ast.Yield, ast.YieldFrom}:
            return expr
        rhs = self.visit(expr.value)
        return ast.Expr(value=rhs)

    def visit_Assert(self, assert_node: ast.Assert):  # noqa: N802
        """Visit Assert statement.

        Args:
            assert_node: the node to visit.

        Returns:
            the transformed node.
        """
        new_test = self.visit(assert_node.test)
        return ast.Assert(test=new_test, msg=assert_node.msg)

    def visit_FunctionDef(self, fn_def_node: ast.FunctionDef):  # noqa: N802
        """Reformat the test in fn_def_node.

         so it can be parsed by initial population seeding module.

        Args:
            fn_def_node: the node to visit.

        Returns:
            the transformed node.
        """
        if not fn_def_node.name.startswith("test_"):
            return fn_def_node

        fn_def_node.args.args = [arg for arg in fn_def_node.args.args if arg.arg != "self"]
        # Visit the main body
        new_body = self.visit_block_helper(fn_def_node.body)
        fn_def_node.body = new_body
        ast.fix_missing_locations(fn_def_node)

        return fn_def_node

    def _convert_class_statement(
        self, stmt: ast.stmt, class_name: str
    ) -> tuple[list[tuple[str, ast.expr]], list[ast.stmt]] | None:
        """Convert a single statement within a helper class body.

        Args:
            stmt: The statement to convert.
            class_name: The name of the class enclosing the statement.

        Returns:
            A tuple of ((attr_name, value_expr) pairs, hoisted_stmts) if convertible,
            or None if the statement cannot be represented dynamically.
        """
        if isinstance(stmt, ast.Pass):
            return ([], [])
        if isinstance(stmt, ast.Expr):
            return ([], []) if isinstance(stmt.value, ast.Constant) else None
        if isinstance(stmt, ast.Assign):
            if not all(isinstance(target, ast.Name) for target in stmt.targets):
                return None
            val = self.visit(stmt.value)
            return (
                [(target.id, val) for target in stmt.targets if isinstance(target, ast.Name)],
                [],
            )
        if isinstance(stmt, ast.AnnAssign):
            if not isinstance(stmt.target, ast.Name):
                return None
            if stmt.value is not None:
                return ([(stmt.target.id, self.visit(stmt.value))], [])
            return ([], [])
        if isinstance(stmt, ast.FunctionDef):
            return self._convert_function_def(stmt, class_name)
        return None

    def _convert_function_def(
        self, stmt: ast.FunctionDef, class_name: str
    ) -> tuple[list[tuple[str, ast.expr]], list[ast.stmt]] | None:
        """Convert a function definition within a helper class body.

        Args:
            stmt: The function definition node.
            class_name: The name of the class enclosing the function.

        Returns:
            A tuple of ((attr_name, value_expr) pairs, hoisted_stmts) if convertible,
            or None if the method contains zero-arg super().
        """
        if _has_zero_arg_super(stmt):
            return None
        fn_name = f"_{class_name}_{stmt.name}"
        if fn_name in self.used_varnames:
            fn_name = self.generate_new_varname()
        else:
            self.used_varnames.add(fn_name)
        hoisted_fn = self._create_hoisted_method(stmt, fn_name)
        return ([(stmt.name, ast.Name(id=fn_name, ctx=ast.Load()))], [hoisted_fn])

    def _create_hoisted_method(self, stmt: ast.FunctionDef, fn_name: str) -> ast.FunctionDef:
        """Create a hoisted function definition with a new name.

        Args:
            stmt: The original function definition inside the class.
            fn_name: The new unique name for the hoisted function.

        Returns:
            The new hoisted ast.FunctionDef node.
        """
        if sys.version_info >= (3, 12):
            hoisted_fn = ast.FunctionDef(
                name=fn_name,
                args=stmt.args,
                body=stmt.body,
                decorator_list=stmt.decorator_list,
                returns=stmt.returns,
                type_comment=stmt.type_comment,
                type_params=getattr(stmt, "type_params", []),
            )
        else:
            hoisted_fn = ast.FunctionDef(
                name=fn_name,
                args=stmt.args,
                body=stmt.body,
                decorator_list=stmt.decorator_list,
                returns=stmt.returns,
                type_comment=stmt.type_comment,
            )
        ast.copy_location(hoisted_fn, stmt)
        ast.fix_missing_locations(hoisted_fn)
        return hoisted_fn

    def _try_convert_class_to_dynamic_type(self, node: ast.ClassDef) -> ast.Assign | None:
        """Attempt to convert a simple helper ClassDef to an assignment with type(...).

        This eliminates PEP 227 scoping violations (NameError when class attributes
        reference enclosing local variables) and flattens class definitions so they
        can participate in GA mutation and crossover.

        Args:
            node: The class definition node to convert.

        Returns:
            An ast.Assign node if the class can be converted, or None otherwise.
        """
        if node.decorator_list or node.keywords or getattr(node, "type_params", None):
            return None

        dict_keys: list[ast.expr | None] = []
        dict_values: list[ast.expr] = []
        hoisted_stmts: list[ast.stmt] = []

        for stmt in node.body:
            converted = self._convert_class_statement(stmt, node.name)
            if converted is None:
                return None
            entries, hoisted = converted
            for key, val in entries:
                dict_keys.append(ast.Constant(value=key))
                dict_values.append(val)
            hoisted_stmts.extend(hoisted)

        bases = [self.visit(b) for b in node.bases]
        bases_tuple = ast.Tuple(elts=bases, ctx=ast.Load())
        namespace_dict = ast.Dict(keys=dict_keys, values=dict_values)
        type_call = ast.Call(
            func=ast.Name(id="type", ctx=ast.Load()),
            args=[ast.Constant(value=node.name), bases_tuple, namespace_dict],
            keywords=[],
        )
        assign = ast.Assign(
            targets=[ast.Name(id=node.name, ctx=ast.Store())],
            value=type_call,
        )
        ast.copy_location(assign, node)
        ast.fix_missing_locations(assign)

        self.used_varnames.add(node.name)
        self.stmts_to_add.extend(hoisted_stmts)
        return assign

    def visit_ClassDef(self, node: ast.ClassDef):  # noqa: N802
        """Transform the class by filtering and taking only test methods.

        If the class is a nested helper class without test methods, normalize it
        to a dynamic type(...) assignment if possible.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        if any(
            isinstance(stmt, ast.FunctionDef) and stmt.name.startswith("test_")
            for stmt in node.body
        ):
            new_body = []
            for stmt in node.body:
                if isinstance(stmt, ast.FunctionDef) and stmt.name.startswith("test_"):
                    new_body.append(rewrite_test(stmt))
                else:
                    new_body.append(stmt)

            if sys.version_info >= (3, 12):
                return ast.ClassDef(
                    name=node.name,
                    bases=node.bases,
                    keywords=node.keywords,
                    body=new_body,
                    decorator_list=node.decorator_list,
                    type_params=[],
                )

            return ast.ClassDef(
                name=node.name,
                bases=node.bases,
                keywords=node.keywords,
                body=new_body,
                decorator_list=node.decorator_list,
            )

        converted = self._try_convert_class_to_dynamic_type(node)
        if converted is not None:
            return converted
        return node

    def visit_For(self, node):  # noqa: N802
        """Visit a for loop node and transform its body and orelse.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        node.body = self.visit_block_helper(node.body)
        node.orelse = self.visit_block_helper(node.orelse)
        return node

    def visit_While(self, node: ast.While):  # noqa: N802
        """Visit a while loop node and transform its body and orelse.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        node.body = self.visit_block_helper(node.body)
        node.orelse = self.visit_block_helper(node.orelse)
        return node

    def visit_If(self, node):  # noqa: N802
        """Visit an if statement node and transform its body and orelse.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        node.body = self.visit_block_helper(node.body)
        node.orelse = self.visit_block_helper(node.orelse)
        return node

    def visit_With(self, node):  # noqa: N802
        """Visit a with statement node and transform its body.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        node.body = self.visit_block_helper(node.body)
        return node

    def visit_Try(self, node: ast.Try):  # noqa: N802
        """Visit a try statement node and transform its body, orelse, and finalbody.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        node.body = self.visit_block_helper(node.body)
        node.orelse = self.visit_block_helper(node.orelse)
        node.finalbody = self.visit_block_helper(node.finalbody)
        return node

    def visit_Lambda(self, node: ast.Lambda):  # noqa: N802
        """Visit a lambda node and transform its body.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        self.enter_new_bound_scope()
        all_args: ast.arguments = node.args
        for arg in all_args.args + all_args.kwonlyargs:
            arg_name = arg.arg
            self._bound_variables.add(arg_name)
        if all_args.kwarg is not None:
            self._bound_variables.add(all_args.kwarg.arg)
        if all_args.vararg is not None:
            self._bound_variables.add(all_args.vararg.arg)
        new_lambda = self.generic_visit(node)
        self.exit_bound_scope()
        return new_lambda

    def get_comprehension_bound_vars(self, node: ast.comprehension) -> list[str]:
        """Get the bound variables for a comprehension node.

        Args:
            node: the node to visit.

        Returns:
            a list of bound variable names.
        """
        return [elem.id for elem in ast.walk(node.target) if isinstance(elem, ast.Name)]

    def _visit_generators_common(self, generators: list[ast.comprehension]):
        """Common logic for visiting comprehension generators.

        Args:
            generators: a list of comprehension nodes.

        Returns:
            a list of transformed comprehension nodes.
        """
        new_generators = []
        for comp in generators:
            self._bound_variables.update(self.get_comprehension_bound_vars(comp))
            new_generators.append(self.visit(comp))
        return new_generators

    def visit_GeneratorExp(  # noqa: N802
        self, node: ast.GeneratorExp
    ) -> ast.GeneratorExp:
        """Visit a generator expression node and transform its body.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        self.enter_new_bound_scope()
        new_generators = self._visit_generators_common(node.generators)
        new_elt = self.visit(node.elt)
        ret_val = ast.GeneratorExp(elt=new_elt, generators=new_generators)
        self.exit_bound_scope()
        return ret_val

    def visit_ListComp(self, node: ast.ListComp) -> ast.ListComp:  # noqa: N802
        """Visit a list comprehension node and transform its body.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        self.enter_new_bound_scope()
        new_generators = self._visit_generators_common(node.generators)
        new_elt = self.visit(node.elt)
        ret_val = ast.ListComp(elt=new_elt, generators=new_generators)
        self.exit_bound_scope()
        return ret_val

    def visit_SetComp(self, node: ast.SetComp) -> ast.SetComp:  # noqa: N802
        """Visit a set comprehension node and transform its body.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        self.enter_new_bound_scope()
        new_generators = self._visit_generators_common(node.generators)
        new_elt = self.visit(node.elt)
        ret_val = ast.SetComp(elt=new_elt, generators=new_generators)
        self.exit_bound_scope()
        return ret_val

    def visit_DictComp(self, node: ast.DictComp) -> ast.DictComp:  # noqa: N802
        """Visit a dict comprehension node and transform its body.

        Args:
            node: the node to visit.

        Returns:
            the transformed node.
        """
        self.enter_new_bound_scope()
        new_generators = self._visit_generators_common(node.generators)
        new_key = self.visit(node.key)
        new_value = self.visit(node.value)
        ret_val = ast.DictComp(key=new_key, value=new_value, generators=new_generators)
        self.exit_bound_scope()
        return ret_val

    def visit_Import(self, node):  # noqa: N802
        """Visit an import statement node.

        Args:
            node: the node to visit.

        Returns:
            the original node.
        """
        return node

    def visit_ImportFrom(self, node):  # noqa: N802
        """Visit an import from statement node.

        Args:
            node: the node to visit.

        Returns:
            the original node.
        """
        return node

    def visit_Await(self, node):  # noqa: N802
        """Visit an await statement node.

        Args:
            node: the node to visit.

        Returns:
            the original node.
        """
        return node

    def visit_AsyncFunctionDef(self, node):  # noqa: N802
        """Visit an async function definition node.

        Args:
            node: the node to visit.

        Returns:
            the original node.
        """
        return node

    def visit_AsyncFor(self, node):  # noqa: N802
        """Visit an async for statement node.

        Args:
            node: the node to visit.

        Returns:
            the original node.
        """
        return node

    def visit_AsyncWith(self, node):  # noqa: N802
        """Visit an async with statement node.

        Args:
            node: the node to visit.

        Returns:
            the original node.
        """
        return node

    def visit_Match(self, node):  # noqa: N802
        """Visit a match statement node.

        Args:
            node: the node to visit.

        Returns:
            the original node.
        """
        return node


@dataclasses.dataclass
class RewrittenTests:
    """The result of rewriting an LLM response into Pynguin-parseable form.

    ``rewrite_tests`` flattens each test into a standalone function, which discards
    the module-level imports the tests rely on (e.g. ``from unittest.mock import
    patch``). Those imports are surfaced separately here so the deserializer can
    re-attach the ones each test actually references.
    """

    #: Rewritten test source keyed by qualified function name (``TestA.test_eq``).
    functions: dict[str, str]
    #: Unparsed source of each top-level import statement, in source order.
    module_imports: list[str]


def _extract_module_level_imports(module_node: ast.Module) -> list[str]:
    """Return the unparsed source of each top-level import in *module_node*."""
    imports: list[str] = []
    for node in module_node.body:
        if isinstance(node, ast.Import | ast.ImportFrom):
            try:
                imports.append(ast.unparse(node))
            except AttributeError as e:  # pragma: no cover - unparse is total for imports
                logger.info("Got error: %s\nwhen trying to unparse a module-level import", e)
    return imports


def rewrite_tests(source: str) -> RewrittenTests:
    """Rewrite the tests in `source` so that they can be parsed.

    By AstToTestCaseTransformer.

    Args:
        source: the source code containing tests.

    Returns:
        the rewritten tests together with the top-level imports they were extracted
        from (see :class:`RewrittenTests`).
    """
    # Sometimes LLM returns function definition with only a comment inside
    # which results in syntax error.
    empty_function_pattern = re.compile(
        r"^\s*def\s+\w+\s*\(.*\):\s*\n\s*#.*?\n(?:\s*\n)*(?=^\s*def|\Z)", re.MULTILINE
    )
    source_without_empty_methods = re.sub(empty_function_pattern, "\n", source)
    source_fixed = fixup_result(source_without_empty_methods)
    module_node: ast.Module = ast.parse(source_fixed)
    module_imports = _extract_module_level_imports(module_node)
    function_definitions = extract_function_defs(module_node)
    functions = process_function_defs(function_definitions, module_node)
    return RewrittenTests(functions=functions, module_imports=module_imports)


def rewrite_test(fn_def_node: ast.FunctionDef):
    """Reformat the test in fn_def_node.

    So it can be parsed by AstToTestCaseTransformer.

    Args:
        fn_def_node: a function definition to rewrite.

    Returns:
        a rewritten AST node.
    """
    visitor = StmtRewriter()
    visitor.visit(fn_def_node)
    return fn_def_node


# Names of fixture methods whose ``self.``/``cls.`` assignments should be inlined into
# each test method. Covers the unittest ``setUp`` as well as the pytest xUnit-style
# fixtures (``setup_method``/``setup`` run before every test, ``setup_class`` once per
# class). Without this, statements using the fixture attributes are dropped as
# unresolved (see issue #303).
SETUP_METHOD_NAMES = frozenset({"setUp", "setup_method", "setup", "setup_class"})


class TestClassRewriter(ast.NodeTransformer):
    """A custom AST node transformer for rewriting test classes."""

    def __init__(self):  # noqa: D107
        self.set_up_vars = []
        self.counter = 0
        self.var_mapping = {}

    def visit_ClassDef(self, node: ast.ClassDef):  # noqa:N802
        """Processes a class definition, collecting setup-fixture variables.

        Args:
            node (ast.ClassDef): The class definition node.

        Returns:
            ast.ClassDef: The transformed class node.
        """
        for child_node in node.body:
            if isinstance(child_node, ast.FunctionDef) and child_node.name in SETUP_METHOD_NAMES:
                self.collect_set_up_vars(child_node)

        for child_node in node.body:
            if isinstance(child_node, ast.FunctionDef) and child_node.name.startswith("test_"):
                self.transform_test_function(child_node)

        return node

    def collect_set_up_vars(self, set_up_node: ast.FunctionDef):
        """Collects variables from a setup fixture, removing the `self.`/`cls.` prefix.

        and stores them with their original attribute names. ``cls.`` is accepted so
        that ``setup_class(cls)`` fixtures are inlined as well.
        """
        for stmt in set_up_node.body:
            if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1:
                target = stmt.targets[0]
                if (
                    isinstance(target, ast.Attribute)
                    and isinstance(target.value, ast.Name)
                    and target.value.id in {"self", "cls"}
                ):
                    var_name = target.attr
                    self.var_mapping[target.attr] = var_name
                    new_target = ast.Name(id=var_name, ctx=ast.Store())
                    self.set_up_vars.append(ast.Assign(targets=[new_target], value=stmt.value))

    def transform_test_function(self, test_func_node: ast.FunctionDef):
        """Transforms a test function by replacing `self.<variable>`.

        references with `var_<counter>` and removing `self` from
        method calls.

        Adds the transformed `setUp` variables to the start of the
        test function body.

        Args:
            test_func_node (ast.FunctionDef): The test function node
            to transform.
        """
        # Add the transformed `setUp` variables at the start of the test function
        test_func_node.body = self.set_up_vars + [
            self.replace_self_references(stmt) for stmt in test_func_node.body
        ]

    def replace_self_references(self, node):
        """Replaces `self.<variable>` references and removes `self` from method calls.

        Args:
            node (ast.AST): The current AST node to process.

        Returns:
            ast.AST: The modified AST node with `self` references replaced.
        """
        # Do not descend into nested scopes: a nested ``def``/``class``/``lambda``
        # introduces its own ``self`` binding (e.g. a locally-defined class whose
        # methods take ``self``), so rewriting ``self.<attr>`` inside it would corrupt
        # legitimate instance-attribute access and produce code that raises at runtime.
        # Only the test method's own ``self`` (the unittest test-class instance) is
        # rewritten.
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef | ast.Lambda):
            return node

        # Handle `self.<variable>` replacement
        if (
            isinstance(node, ast.Attribute)
            and isinstance(node.value, ast.Name)
            and node.value.id == "self"
        ):
            # Check if it's a variable reference or a method call
            return (
                ast.Name(id=self.var_mapping[node.attr], ctx=node.ctx)
                if node.attr in self.var_mapping
                else ast.Name(id=node.attr, ctx=node.ctx)
            )

        # Process any child nodes recursively
        for field, value in ast.iter_fields(node):
            if isinstance(value, list):
                new_values = [
                    (self.replace_self_references(item) if isinstance(item, ast.AST) else item)
                    for item in value
                ]
                setattr(node, field, new_values)
            elif isinstance(value, ast.AST):
                new_value = self.replace_self_references(value)
                setattr(node, field, new_value)

        return node


def extract_function_defs(module_node: ast.Module) -> list[tuple[str, ast.FunctionDef]]:
    """Extract test function definitions with updated `setUp` variables.

    without `self` prefix.

    Args:
        module_node: the module node to extract the test functions from.

    Returns:
        pairs of qualified name and function definition, in source order. Test
        methods are qualified with their class name (``TestA.test_eq``), because LLMs
        often reuse method names across test classes.
    """
    assert isinstance(module_node, ast.Module)

    rewriter = TestClassRewriter()
    rewriter.visit(module_node)

    test_functions: list[tuple[str, ast.FunctionDef]] = []
    for node in module_node.body:
        # Top-level test functions
        if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
            test_functions.append((node.name, node))

        # Test methods inside classes
        elif isinstance(node, ast.ClassDef):
            test_functions.extend(
                (f"{node.name}.{child_node.name}", child_node)
                for child_node in node.body
                if isinstance(child_node, ast.FunctionDef) and child_node.name.startswith("test_")
            )

    return test_functions


def process_function_defs(
    function_defs: list[tuple[str, ast.FunctionDef]], module_node: ast.Module
) -> dict[str, str]:
    """Process the extracted FunctionDef nodes and return rewritten tests.

    Args:
        function_defs: pairs of qualified name and function definition node.
        module_node: the module node containing the function definitions.

    Returns:
        a dictionary with qualified function names as keys and rewritten tests as
        values. Duplicate names get a numeric suffix, so no test is lost.
    """
    return_tests: dict[str, str] = {}
    for name, function_def in function_defs:
        test_module = ast.Module(
            body=[rewrite_test(function_def)],
            type_ignores=module_node.type_ignores,
        )
        test_module = ast.fix_missing_locations(test_module)
        try:
            source = ast.unparse(test_module) + "\n"
        except AttributeError as e:
            logger.info("Got error: %s\nwhen trying to unparse the transformation", e)
            continue
        key = name
        suffix = 1
        while key in return_tests:
            suffix += 1
            key = f"{name}_{suffix}"
        return_tests[key] = source
    return return_tests


def fixup_result(result):
    """In case we aborted generation early (due to running out of tokens).

    Remove any lingering syntax errors that prevent parsing by the `ast` module.
    There may still be syntax errors when actually running the code.

    Args:
        result: some natural language source code.

    Returns:
        source code that parses with ast.parse.
    """
    try:
        ast.parse(result)
        return result
    except SyntaxError as e:
        line_to_rm = e.lineno
        lines = result.split("\n")
        if line_to_rm is None or line_to_rm >= len(lines):
            return fixup_result("\n".join(lines[:-1]))
        return fixup_result("\n".join(lines[:line_to_rm]))
